# Project: ÏîÄ¿1
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o modbus_common.o modbus_registers.o
LINKOBJ  = main.o modbus_common.o modbus_registers.o
LIBS     = -L"D:/jiexun/Program Files/Dev-Cpp/MinGW64/lib" -L"D:/jiexun/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/jiexun/Program Files/Dev-Cpp/MinGW64/include" -I"D:/jiexun/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/jiexun/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/jiexun/Program Files/Dev-Cpp/MinGW64/include" -I"D:/jiexun/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/jiexun/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/jiexun/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = testModbus_common.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

modbus_common.o: modbus_common.c
	$(CPP) -c modbus_common.c -o modbus_common.o $(CXXFLAGS)

modbus_registers.o: modbus_registers.c
	$(CPP) -c modbus_registers.c -o modbus_registers.o $(CXXFLAGS)
